// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.BlazorApp.Data;

#nullable disable

namespace Portfolio.BlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130131959_HealthAddedToHeroAndSoldier")]
    partial class HealthAddedToHeroAndSoldier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.BlazorApp.Data.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDamage")
                        .HasColumnType("int");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("int");

                    b.Property<int>("HealthByLevel")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDamage = 12,
                            BaseDefense = 6,
                            HealthByLevel = 0,
                            Level = 5,
                            Name = "Arthas"
                        },
                        new
                        {
                            Id = 2,
                            BaseDamage = 10,
                            BaseDefense = 8,
                            HealthByLevel = 0,
                            Level = 4,
                            Name = "Lyra"
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.HeroItem", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("HeroId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("HeroItems");

                    b.HasData(
                        new
                        {
                            HeroId = 1,
                            ItemId = 1
                        },
                        new
                        {
                            HeroId = 1,
                            ItemId = 7
                        },
                        new
                        {
                            HeroId = 2,
                            ItemId = 2
                        },
                        new
                        {
                            HeroId = 2,
                            ItemId = 6
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 10,
                            Defense = 0,
                            Name = "Iron Sword"
                        },
                        new
                        {
                            Id = 2,
                            Damage = 8,
                            Defense = 0,
                            Name = "Longbow"
                        },
                        new
                        {
                            Id = 3,
                            Damage = 12,
                            Defense = 0,
                            Name = "Fire Staff"
                        },
                        new
                        {
                            Id = 4,
                            Damage = 6,
                            Defense = 0,
                            Name = "Dagger"
                        },
                        new
                        {
                            Id = 5,
                            Damage = 14,
                            Defense = 0,
                            Name = "War Axe"
                        },
                        new
                        {
                            Id = 6,
                            Damage = 0,
                            Defense = 5,
                            Name = "Leather Armor"
                        },
                        new
                        {
                            Id = 7,
                            Damage = 0,
                            Defense = 8,
                            Name = "Iron Shield"
                        },
                        new
                        {
                            Id = 8,
                            Damage = 0,
                            Defense = 10,
                            Name = "Chainmail"
                        },
                        new
                        {
                            Id = 9,
                            Damage = 0,
                            Defense = 7,
                            Name = "Magic Cloak"
                        },
                        new
                        {
                            Id = 10,
                            Damage = 0,
                            Defense = 12,
                            Name = "Tower Shield"
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Demo Player"
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.PlayerHero", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "HeroId");

                    b.HasIndex("HeroId");

                    b.ToTable("PlayerHeroes");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            HeroId = 1
                        },
                        new
                        {
                            PlayerId = 1,
                            HeroId = 2
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.PlayerItem", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("PlayerItems");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            ItemId = 1
                        },
                        new
                        {
                            PlayerId = 1,
                            ItemId = 2
                        },
                        new
                        {
                            PlayerId = 1,
                            ItemId = 6
                        },
                        new
                        {
                            PlayerId = 1,
                            ItemId = 7
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.PlayerSoldier", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SoldierId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "SoldierId");

                    b.HasIndex("SoldierId");

                    b.ToTable("PlayerSoldiers");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            SoldierId = 1
                        },
                        new
                        {
                            PlayerId = 1,
                            SoldierId = 2
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.Soldier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDamage")
                        .HasColumnType("int");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("int");

                    b.Property<int>("HealthByLevel")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Soldiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDamage = 6,
                            BaseDefense = 4,
                            HealthByLevel = 0,
                            Level = 2,
                            Name = "Footman"
                        },
                        new
                        {
                            Id = 2,
                            BaseDamage = 7,
                            BaseDefense = 3,
                            HealthByLevel = 0,
                            Level = 2,
                            Name = "Archer"
                        });
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.HeroItem", b =>
                {
                    b.HasOne("Portfolio.BlazorApp.Data.Hero", "Hero")
                        .WithMany("EquippedItems")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.BlazorApp.Data.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.PlayerHero", b =>
                {
                    b.HasOne("Portfolio.BlazorApp.Data.Hero", "Hero")
                        .WithMany("PlayerHeroes")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.BlazorApp.Data.Player", "Player")
                        .WithMany("PlayerHeroes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.PlayerItem", b =>
                {
                    b.HasOne("Portfolio.BlazorApp.Data.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.BlazorApp.Data.Player", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.PlayerSoldier", b =>
                {
                    b.HasOne("Portfolio.BlazorApp.Data.Player", "Player")
                        .WithMany("PlayerSoldiers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.BlazorApp.Data.Soldier", "Soldier")
                        .WithMany("PlayerSoldiers")
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.Hero", b =>
                {
                    b.Navigation("EquippedItems");

                    b.Navigation("PlayerHeroes");
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.Player", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("PlayerHeroes");

                    b.Navigation("PlayerSoldiers");
                });

            modelBuilder.Entity("Portfolio.BlazorApp.Data.Soldier", b =>
                {
                    b.Navigation("PlayerSoldiers");
                });
#pragma warning restore 612, 618
        }
    }
}
